apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tibco-bwce-order-service-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nubenetes/jenkins-git-parameter-bwce.git
    targetRevision: main
    path: sample-apps/tibco-bwce-order-service/k8s/overlays/staging
  destination:
    name: ocp-staging-cluster
    namespace: nubenetes-staging-bwce
